export const amiibos = [
  {
    name: "Kicks",
    image: "kicks",
    series: "Animal Crossing",
    release: "2015-12-17",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Kirby",
    image: "kirby",
    series: "Kirby",
    release: "2016-04-28",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Meta Knight",
    image: "meta-knight",
    series: "Kirby",
    release: "2016-04-28",
    owned: true,
    type: "amiibos",
  },
  {
    name: "King Dedede",
    image: "dedede",
    series: "Kirby",
    release: "2016-04-28",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Waddle Dee",
    image: "waddle",
    series: "Kirby",
    release: "2016-04-28",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Samus Aran",
    image: "samus-aran",
    series: "Metroid",
    release: "2017-09-15",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Metroid",
    image: "metroid",
    series: "Metroid",
    release: "2017-09-15",
    owned: false,
    type: "amiibos",
  },
  {
    name: "Samus",
    image: "samus",
    series: "Metroid",
    release: "2021-10-08",
    owned: true,
    type: "amiibos",
  },
  {
    name: "E.M.M.I.",
    image: "emmi",
    series: "Metroid",
    release: "2021-10-08",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Inkling Squid",
    image: "squid",
    series: "Splatoon",
    release: "2015-05-28",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Mario",
    image: "mario",
    series: "Super Mario",
    release: "2015-03-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Luigi",
    image: "luigi",
    series: "Super Mario",
    release: "2015-03-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Peach",
    image: "peach",
    series: "Super Mario",
    release: "2015-03-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Bowser",
    image: "bowser",
    series: "Super Mario",
    release: "2015-03-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Wario",
    image: "wario",
    series: "Super Mario",
    release: "2016-10-07",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Boo",
    image: "boo",
    series: "Super Mario",
    release: "2016-10-07",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Donkey Kong",
    image: "donkey",
    series: "Super Mario",
    release: "2016-10-07",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Waluigi",
    image: "waluigi",
    series: "Super Mario",
    release: "2016-10-20",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Mario Wedding Outfit",
    image: "mario-wedding",
    series: "Super Mario",
    release: "2017-10-27",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Peach Wedding Outfit",
    image: "peach-wedding",
    series: "Super Mario",
    release: "2017-10-27",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Bowser Wedding Outfit",
    image: "bowser-wedding",
    series: "Super Mario",
    release: "2017-10-27",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Cat Mario",
    image: "cat-mario",
    series: "Super Mario",
    release: "2021-02-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Cat Peach",
    image: "cat-peach",
    series: "Super Mario",
    release: "2021-02-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Mario Classic Colors",
    image: "mario-classic",
    series: "Super Mario Bros. 30th Anniversary",
    release: "2015-09-10",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Wolf Link",
    image: "wolf-link",
    series: "The Legend of Zelda",
    release: "2016-03-04",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link The Legend of Zelda",
    image: "link-classic",
    series: "The Legend of Zelda",
    release: "2016-12-01",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Ocarina of Time",
    image: "link-oot",
    series: "The Legend of Zelda",
    release: "2016-12-01",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Toon Link The Wind Waker",
    image: "link-ww",
    series: "The Legend of Zelda",
    release: "2016-12-01",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Zelda The Wind Waker",
    image: "zelda-ww",
    series: "The Legend of Zelda",
    release: "2016-12-01",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Archer",
    image: "link-archer",
    series: "The Legend of Zelda",
    release: "2017-03-03",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Rider",
    image: "link-rider",
    series: "The Legend of Zelda",
    release: "2017-03-03",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Guardian",
    image: "guardian",
    series: "The Legend of Zelda",
    release: "2017-03-03",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Zelda",
    image: "zelda-botw",
    series: "The Legend of Zelda",
    release: "2017-03-03",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Bokoblin",
    image: "bokoblin",
    series: "The Legend of Zelda",
    release: "2017-03-03",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Majora's Mask",
    image: "link-majora",
    series: "The Legend of Zelda",
    release: "2017-06-23",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Twilight Princess",
    image: "link-tp",
    series: "The Legend of Zelda",
    release: "2017-06-23",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Skyward Sword",
    image: "link-ss",
    series: "The Legend of Zelda",
    release: "2017-06-23",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Mipha Zora Champion",
    image: "mipha",
    series: "The Legend of Zelda",
    release: "2017-11-10",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Daruk Goron Champion",
    image: "daruk",
    series: "The Legend of Zelda",
    release: "2017-11-10",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Revali Rito Champion",
    image: "revali",
    series: "The Legend of Zelda",
    release: "2017-11-10",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Urbosa Gerudo Champion",
    image: "urbosa",
    series: "The Legend of Zelda",
    release: "2017-11-10",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Link's Awakening",
    image: "link-la",
    series: "The Legend of Zelda",
    release: "2019-09-20",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Zelda & Loftwing Skyward Sword",
    image: "zelda-ss",
    series: "The Legend of Zelda",
    release: "2021-07-16",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link Tears of the Kingdom",
    image: "link-totk",
    series: "The Legend of Zelda",
    release: "2023-05-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Zelda Tears of the Kingdom",
    image: "zelda-totk",
    series: "The Legend of Zelda",
    release: "2023-11-03",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Ganondorf Tears of the Kingdom",
    image: "ganon-totk",
    series: "The Legend of Zelda",
    release: "2023-11-03",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Link",
    image: "link-smash",
    series: "Super Smash Bros.",
    release: "2014-11-21",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Samus",
    image: "samus-smash",
    series: "Super Smash Bros.",
    release: "2014-11-21",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Wii Fit Trainer",
    image: "wii-smash",
    series: "Super Smash Bros.",
    release: "2014-11-21",
    owned: false,
    type: "amiibos",
  },
  {
    name: "Zelda",
    image: "zelda-smash",
    series: "Super Smash Bros.",
    release: "2014-12-06",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Toon Link",
    image: "toon-link-smash",
    series: "Super Smash Bros.",
    release: "2015-01-22",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Sheik",
    image: "sheik-smash",
    series: "Super Smash Bros.",
    release: "2015-01-22",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Mega Man",
    image: "mega-man",
    series: "Super Smash Bros.",
    release: "2015-01-29",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Charizard",
    image: "charizard",
    series: "Super Smash Bros.",
    release: "2015-04-24",
    owned: false,
    type: "amiibos",
  },
  {
    name: "Pac-Man",
    image: "pac-man",
    series: "Super Smash Bros.",
    release: "2015-04-24",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Zero Suit Samus",
    image: "zero-samus",
    series: "Super Smash Bros.",
    release: "2015-06-11",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Ganondorf",
    image: "ganon-smash",
    series: "Super Smash Bros.",
    release: "2015-06-11",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Mewtwo",
    image: "mewtwo",
    series: "Super Smash Bros.",
    release: "2015-10-23",
    owned: false,
    type: "amiibos",
  },
  {
    name: "Bayonetta Player 2",
    image: "bayonetta",
    series: "Super Smash Bros.",
    release: "2017-07-21",
    owned: false,
    type: "amiibos",
  },
  {
    name: "Ridley",
    image: "ridley",
    series: "Super Smash Bros.",
    release: "2018-12-07",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Piranha Plant",
    image: "piranha",
    series: "Super Smash Bros.",
    release: "2019-02-15",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Young Link",
    image: "young-link",
    series: "Super Smash Bros.",
    release: "2019-04-12",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Simon",
    image: "simon",
    series: "Super Smash Bros.",
    release: "2019-11-08",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Dark Samus",
    image: "dark-samus",
    series: "Super Smash Bros.",
    release: "2020-01-17",
    owned: true,
    type: "amiibos",
  },
  {
    name: "Richter",
    image: "richter",
    series: "Super Smash Bros.",
    release: "2020-01-17",
    owned: true,
    type: "amiibos",
  },
];
