export const games = [
  {
    name: "Super Mario Land",
    image: "co7o14",
    series: "Super Mario",
    release: "1990-09-28",
    owned: true,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Dream Land",
    image: "co3ffy",
    series: "Kirby",
    release: "1992-08-03",
    owned: true,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario Land 2: 6 Golden Coins",
    image: "co7gxg",
    series: "Super Mario",
    release: "1993-01-28",
    owned: true,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Link's Awakening",
    image: "co3nnt",
    series: "The Legend of Zelda",
    release: "1993-12-01",
    owned: true,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Wario Land: Super Mario Land 3",
    image: "co216h",
    series: "Wario Land",
    release: "1994-05-13",
    owned: true,
    platforms: ["Nintendo Game Boy"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Dream Land 2",
    image: "co7crs",
    series: "Kirby",
    release: "1995-07-31",
    owned: true,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Link's Awakening DX",
    image: "co5war",
    series: "The Legend of Zelda",
    release: "1999-01-01",
    owned: true,
    platforms: ["Nintendo Game Boy Color"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario Bros. Deluxe",
    image: "co2299",
    series: "Super Mario",
    release: "1999-07-01",
    owned: true,
    platforms: ["Nintendo Game Boy Color"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wario Land 3",
    image: "co54lp",
    series: "Wario Land",
    release: "2000-04-14",
    owned: true,
    platforms: ["Nintendo Game Boy Color"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Oracle of Ages",
    image: "co2tw1",
    series: "The Legend of Zelda",
    release: "2001-10-05",
    owned: true,
    platforms: ["Nintendo Game Boy Color"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Oracle of Seasons",
    image: "co2tw0",
    series: "The Legend of Zelda",
    release: "2001-10-05",
    owned: true,
    platforms: ["Nintendo Game Boy Color"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Ocarina of Time + The Legend of Zelda: Ocarina of Time: Master Quest: Two-game Bonus Disc!",
    image: "co5vvd",
    series: "The Legend of Zelda",
    release: "2003-05-03",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Twilight Princess",
    image: "co3w1h",
    series: "The Legend of Zelda",
    release: "2006-12-08",
    owned: true,
    platforms: ["Nintendo GameCube", "Nintendo Wii"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Four Swords Adventures",
    image: "co3p4n",
    series: "The Legend of Zelda",
    release: "2005-01-07",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Collector's Edition",
    image: "co4n26",
    series: "The Legend of Zelda",
    release: "2003-11-14",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Smash Bros. Melee",
    image: "co21yv",
    series: "Super Smash Bros.",
    release: "2002-05-24",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Smash Bros. Ultimate",
    image: "co2255",
    series: "Super Smash Bros.",
    release: "2018-12-07",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 40,
    type: "games",
  },
  {
    name: "Super Smash Bros. Brawl",
    image: "co60ua",
    series: "Super Smash Bros.",
    release: "2008-06-27",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby Air Ride",
    image: "co6nwh",
    series: "Kirby",
    release: "2004-02-27",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "SoulCalibur II",
    image: "co61zk",
    series: "SoulCalibur",
    release: "2003-09-26",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Mega Collection",
    image: "co2v6h",
    series: "Sonic the Hedgehog",
    release: "2003-03-07",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Gems Collection",
    image: "co29p3",
    series: "Sonic the Hedgehog",
    release: "2005-09-30",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Adventure DX: Director's Cut",
    image: "co1te5",
    series: "Sonic the Hedgehog",
    release: "2003-06-27",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Adventure 2: Battle",
    image: "co5p3m",
    series: "Sonic the Hedgehog",
    release: "2002-05-03",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: The Wind Waker HD",
    image: "co54x0",
    series: "The Legend of Zelda",
    release: "2013-10-04",
    owned: true,
    platforms: ["Nintendo Wii U"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Breath of the Wild",
    image: "co54wz",
    series: "The Legend of Zelda",
    release: "2017-03-03",
    owned: true,
    platforms: ["Nintendo Wii U", "Nintendo Switch"],
    completed: true,
    hours: 100,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Tears of the Kingdom",
    image: "co5vmg",
    series: "The Legend of Zelda",
    release: "2023-05-12",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 120,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Majora's Mask 3D",
    image: "co1ujb",
    series: "The Legend of Zelda",
    release: "2015-02-13",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Ocarina of Time 3D",
    image: "co600v",
    series: "The Legend of Zelda",
    release: "2011-06-17",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: A Link Between Worlds",
    image: "co54x4",
    series: "The Legend of Zelda",
    release: "2013-11-22",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Twilight Princess HD",
    image: "co54wt",
    series: "The Legend of Zelda",
    release: "2016-03-04",
    owned: true,
    platforms: ["Nintendo Wii U"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: The Minish Cap",
    image: "co54ws",
    series: "The Legend of Zelda",
    release: "2004-11-12",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Classic NES Series: The Legend of Zelda",
    image: "co5wss",
    series: "The Legend of Zelda",
    release: "2004-07-09",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Classic NES Series: Zelda II: The Adventure of Link",
    image: "co5wsu",
    series: "The Legend of Zelda",
    release: "2005-01-07",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Link's Awakening",
    image: "co1qve",
    series: "The Legend of Zelda",
    release: "2019-09-20",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 16,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Skyward Sword HD",
    image: "co3p3a",
    series: "The Legend of Zelda",
    release: "2021-07-16",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 37,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Phantom Hourglass",
    image: "co54wu",
    series: "The Legend of Zelda",
    release: "2007-10-19",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Spirit Tracks",
    image: "co54wv",
    series: "The Legend of Zelda",
    release: "2009-12-11",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Hyrule Warriors",
    image: "co54x2",
    series: "The Legend of Zelda",
    release: "2014-09-19",
    owned: true,
    platforms: ["Nintendo Wii U"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Hyrule Warriors: Legends",
    image: "co54x3",
    series: "The Legend of Zelda",
    release: "2016-03-24",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Hyrule Warriors: Definitive Edition",
    image: "co2f7y",
    series: "The Legend of Zelda",
    release: "2018-05-18",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 50,
    type: "games",
  },
  {
    name: "Hyrule Warriors: Age of Calamity",
    image: "co3p4a",
    series: "The Legend of Zelda",
    release: "2020-11-19",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 45,
    type: "games",
  },
  {
    name: "Link's Crossbow Training",
    image: "co3ocw",
    series: "The Legend of Zelda",
    release: "2007-12-07",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: A Link to the Past & Four Swords",
    image: "co54x5",
    series: "The Legend of Zelda",
    release: "2003-03-28",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Tri Force Heroes",
    image: "co3p1a",
    series: "The Legend of Zelda",
    release: "2015-10-23",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Nintendo Land",
    image: "co1p9c",
    release: "2012-11-30",
    owned: true,
    platforms: ["Nintendo Wii U"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Cadence of Hyrule: Crypt of the NecroDancer Featuring the Legend of Zelda",
    image: "co1qgt",
    series: "The Legend of Zelda",
    release: "2019-06-13",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 8,
    type: "games",
  },
  {
    name: "Paper Mario: Sticker Star",
    image: "co1tfp",
    series: "Paper Mario",
    release: "2012-12-07",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Paper Mario: Color Splash",
    image: "co213w",
    series: "Paper Mario",
    release: "2016-10-07",
    owned: true,
    platforms: ["Nintendo Wii U"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Paper Mario",
    image: "co7pwr",
    series: "Paper Mario",
    release: "2007-09-14",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Paper Mario: The Origami King",
    image: "co2sai",
    series: "Paper Mario",
    release: "2020-07-17",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 34,
    type: "games",
  },
  {
    name: "Paper Mario: The Thousand-Year Door",
    image: "co83vd",
    series: "Paper Mario",
    release: "2024-05-23",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 40,
    type: "games",
  },
  {
    name: "Super Mario All-Stars: 25th Anniversary Edition",
    image: "co2vvc",
    series: "Super Mario",
    release: "2010-12-03",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario 3D All-Stars",
    image: "co2mf8",
    series: "Super Mario",
    release: "2020-09-18",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 50,
    type: "games",
  },
  {
    name: "Super Mario Galaxy",
    image: "co21ro",
    series: "Super Mario",
    release: "2007-11-16",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario Galaxy 2",
    image: "co21tl",
    series: "Super Mario",
    release: "2010-06-11",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario 64 DS",
    image: "co2u80",
    series: "Super Mario",
    release: "2005-03-11",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario Advance: Super Mario Bros. 2 & Mario Bros.",
    image: "co21r7",
    series: "Super Mario",
    release: "2001-06-22",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario World: Super Mario Advance 2",
    image: "co6nhk",
    series: "Super Mario",
    release: "2002-02-12",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario Advance 4: Super Mario Bros. 3",
    image: "co229t",
    series: "Super Mario",
    release: "2003-10-17",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario 3D Land",
    image: "co21tq",
    series: "Super Mario",
    release: "2011-11-18",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario 3D World",
    image: "co21vd",
    series: "Super Mario",
    release: "2013-11-29",
    owned: true,
    platforms: ["Nintendo Wii U"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario 3D World + Bowser's Fury",
    image: "co2uo9",
    series: "Super Mario",
    release: "2021-02-12",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 18,
    type: "games",
  },
  {
    name: "Captain Toad: Treasure Tracker",
    image: "co6c6f",
    series: "Captain Toad",
    release: "2018-07-13",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 12,
    type: "games",
  },
  {
    name: "Kirby and the Rainbow Paintbrush",
    image: "co1wcc",
    series: "Kirby",
    release: "2015-05-08",
    owned: true,
    platforms: ["Nintendo Wii U"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Rhapsody: A Musical Adventure",
    image: "co4pun",
    series: "Marl Kingdom",
    release: "2008-09-23",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Rhapsody: Marl Kingdom Chronicles",
    image: "co6znp",
    series: "Marl Kingdom",
    release: "2023-09-01",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 40,
    type: "games",
  },
  {
    name: "Luigi's Mansion",
    image: "co1wmb",
    series: "Luigi's Mansion",
    release: "2018-10-19",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Luigi's Mansion 2",
    image: "co6hoj",
    series: "Luigi's Mansion",
    release: "2013-03-28",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Luigi's Mansion 2 HD",
    image: "co88er",
    series: "Luigi's Mansion",
    release: "2024-06-27",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 18,
    type: "games",
  },
  {
    name: "Luigi's Mansion 3",
    image: "co22a9",
    series: "Luigi's Mansion",
    release: "2019-10-31",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 17,
    type: "games",
  },
  {
    name: "Yoshi's New Island",
    image: "co2f6u",
    series: "Yoshi",
    release: "2014-03-14",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Yoshi's Island DS",
    image: "co4wgl",
    series: "Yoshi",
    release: "2006-12-01",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "WarioWare: Smooth Moves",
    image: "co54lt",
    series: "WarioWare",
    release: "2007-01-12",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wario Land 4",
    image: "co1wpx",
    series: "Wario Land",
    release: "2001-11-16",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Wario Land: The Shake Dimension",
    image: "co54lr",
    series: "Wario Land",
    release: "2008-09-26",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Metroid: Samus Returns",
    image: "co3j82",
    series: "Metroid",
    release: "2017-09-15",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Metroid Dread",
    image: "co39zx",
    series: "Metroid",
    release: "2021-10-07",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 12,
    type: "games",
  },
  {
    name: "Metroid Prime Remastered",
    image: "co658o",
    series: "Metroid",
    release: "2023-02-08",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 16,
    type: "games",
  },
  {
    name: "Kirby: Nightmare in Dream Land",
    image: "co1wcd",
    series: "Kirby",
    release: "2003-09-26",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Extra Epic Yarn",
    image: "co69p5",
    series: "Kirby",
    release: "2019-03-08",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Adventure Wii",
    image: "co54h3",
    series: "Kirby",
    release: "2011-11-25",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Return to Dream Land Deluxe",
    image: "co8dp2",
    series: "Kirby",
    release: "2023-02-24",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 11,
    type: "games",
  },
  {
    name: "Kirby Mass Attack",
    image: "co7c0b",
    series: "Kirby",
    release: "2011-10-28",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby: Mouse Attack",
    image: "co4385",
    series: "Kirby",
    release: "2007-06-22",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby Super Star Ultra",
    image: "co3g9j",
    series: "Kirby",
    release: "2008-09-22",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby & the Amazing Mirror",
    image: "co751t",
    series: "Kirby",
    release: "2004-04-15",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby Triple Deluxe",
    image: "co1q9m",
    series: "Kirby",
    release: "2014-05-16",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby: Planet Robobot",
    image: "co1wco",
    series: "Kirby",
    release: "2016-06-10",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kid Icarus: Uprising",
    image: "co1wwr",
    series: "Kid Icarus",
    release: "2012-03-23",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "New Super Mario Bros.",
    image: "co73ye",
    series: "Super Mario",
    release: "2006-06-30",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "New Super Mario Bros. 2",
    image: "co21tr",
    series: "Super Mario",
    release: "2012-08-17",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "New Super Mario Bros. Wii",
    image: "co21tj",
    series: "Super Mario",
    release: "2009-11-20",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "New Super Mario Bros. U Deluxe",
    image: "co1uhl",
    series: "Super Mario",
    release: "2019-01-11",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 17,
    type: "games",
  },
  {
    name: "Golden Sun",
    image: "co1uca",
    series: "Golden Sun",
    release: "2002-02-22",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Golden Sun: The Lost Age",
    image: "co25rt",
    series: "Golden Sun",
    release: "2003-09-19",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Golden Sun: Dark Dawn",
    image: "co25qp",
    series: "Golden Sun",
    release: "2010-12-10",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Chrono Trigger",
    image: "co54iw",
    series: "Chrono",
    release: "2009-02-06",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Advance",
    image: "co1upk",
    series: "Sonic the Hedgehog",
    release: "2002-03-08",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Advance 2",
    image: "co1zv8",
    series: "Sonic the Hedgehog",
    release: "2003-03-28",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Advance 3",
    image: "co1zvg",
    series: "Sonic the Hedgehog",
    release: "2004-06-18",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic the Hedgehog Genesis",
    image: "co1zv3",
    series: "Sonic the Hedgehog",
    release: "2006-12-14",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Generations",
    image: "co1zya",
    series: "Sonic the Hedgehog",
    release: "2011-11-25",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Shadow the Hedgehog",
    image: "co1up3",
    series: "Sonic the Hedgehog",
    release: "2005-11-18",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Meteos",
    image: "co2qop",
    series: "Meteos",
    release: "2005-09-23",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Rhythm Heaven",
    image: "co2e11",
    series: "Rhythm Heaven",
    release: "2009-05-01",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Ōkamiden",
    image: "co3df2",
    series: "Ōkami",
    release: "2011-03-18",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Ōkami",
    image: "co3mpk",
    series: "Ōkami",
    release: "2008-06-13",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Attack of the Saiyans",
    image: "co3dh2",
    series: "Dragon Ball",
    release: "2009-11-06",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Budokai",
    image: "co55ah",
    series: "Dragon Ball",
    release: "2002-11-02",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Budokai 2",
    image: "co5fki",
    series: "Dragon Ball",
    release: "2003-11-14",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Budokai 3",
    image: "co55ai",
    series: "Dragon Ball",
    release: "2004-12-03",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Infinite World",
    image: "co3tse",
    series: "Dragon Ball",
    release: "2008-11-04",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Budokai Tenkaichi",
    image: "co55am",
    series: "Dragon Ball",
    release: "2005-10-21",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Budokai Tenkaichi 2",
    image: "co55al",
    series: "Dragon Ball",
    release: "2006-11-03",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Budokai Tenkaichi 3",
    image: "co55an",
    series: "Dragon Ball",
    release: "2008-02-15",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Dragon Ball Z",
    image: "co54v5",
    series: "Dragon Ball",
    release: "2006-07-14",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball: Final Bout",
    image: "co54d4",
    series: "Dragon Ball",
    release: "1997-11-06",
    owned: true,
    platforms: ["Sony PlayStation"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Burst Limit",
    image: "co1wa9",
    series: "Dragon Ball",
    release: "2008-06-06",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Raging Blast",
    image: "co3u4f",
    series: "Dragon Ball",
    release: "2009-11-13",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Raging Blast 2",
    image: "co54va",
    series: "Dragon Ball",
    release: "2010-11-05",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball: Advanced Adventure",
    image: "co54v6",
    series: "Dragon Ball",
    release: "2005-06-17",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Supersonic Warriors",
    image: "co54vi",
    series: "Dragon Ball",
    release: "2004-08-27",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball: Revenge of King Piccolo",
    image: "co2ilp",
    series: "Dragon Ball",
    release: "2009-10-30",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball Z: Extreme Butouden",
    image: "co1u99",
    series: "Dragon Ball",
    release: "2015-10-16",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "SoulCalibur",
    image: "co1x6g",
    series: "SoulCalibur",
    release: "1999-12-01",
    owned: true,
    platforms: ["Sega Dreamcast"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "SoulCalibur III",
    image: "co54l3",
    series: "SoulCalibur",
    release: "2005-11-18",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "SoulCalibur IV",
    image: "co1x6k",
    series: "SoulCalibur",
    release: "2008-07-31",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Soul Blade",
    image: "co8c9w",
    series: "SoulCalibur",
    release: "1997-05-01",
    owned: true,
    platforms: ["Sony PlayStation"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Star Fox 64 3D",
    image: "co1wwu",
    series: "Star Fox",
    release: "2011-09-09",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Donkey Kong Country Returns 3D",
    image: "co1wf5",
    series: "Donkey Kong Country",
    release: "2013-05-24",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Ultimate NES Remix",
    image: "co2dzu",
    series: "Ultimate NES",
    release: "2014-11-07",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Pokémon Alpha Sapphire",
    image: "co56ef",
    series: "Pokémon",
    release: "2014-11-28",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania Judgment",
    image: "co3z4e",
    series: "Castlevania",
    release: "2009-03-20",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Ocarina of Time",
    image: "co54wx",
    series: "The Legend of Zelda",
    release: "1998-12-11",
    owned: true,
    platforms: ["Nintendo 64"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Majora's Mask",
    image: "co54ww",
    series: "The Legend of Zelda",
    release: "2000-11-17",
    owned: true,
    platforms: ["Nintendo 64"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: The Wind Waker",
    image: "co54wy",
    series: "The Legend of Zelda",
    release: "2003-05-02",
    owned: true,
    platforms: ["Nintendo GameCube"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Skyward Sword",
    image: "co5wrj",
    series: "The Legend of Zelda",
    release: "2011-11-18",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Ball: Xenoverse 2",
    image: "co1u95",
    series: "Dragon Ball",
    release: "2017-09-22",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 40,
    type: "games",
  },
  {
    name: "Tenchu: Stealth Assassins",
    image: "co2f38",
    series: "Tenchu",
    release: "1998-10-30",
    owned: true,
    platforms: ["Sony PlayStation"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Tenchu 2: Birth of the Stealth Assassins",
    image: "co2f37",
    series: "Tenchu",
    release: "2000-10-03",
    owned: true,
    platforms: ["Sony PlayStation"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Tenchu: Wrath of Heaven",
    image: "co1p2e",
    series: "Tenchu",
    release: "2003-03-07",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Tenchu: Fatal Shadows",
    image: "co1p2d",
    series: "Tenchu",
    release: "2005-05-06",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Tenchu Z",
    image: "co2ivp",
    series: "Tenchu",
    release: "2007-06-29",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Fable II",
    image: "co1y2h",
    series: "Fable",
    release: "2008-10-24",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Fable III",
    image: "co231s",
    series: "Fable",
    release: "2010-10-29",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "X-Men Origins: Wolverine: Uncaged Edition",
    image: "co8f4l",
    series: "X-Men",
    release: "2009-05-01",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Grand Theft Auto IV",
    image: "co2lbv",
    series: "Grand Theft Auto",
    release: "2008-04-29",
    owned: true,
    platforms: ["Microsoft Xbox 360"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Street Fighter Anniversary Collection",
    image: "co6ber",
    series: "Street Fighter",
    release: "2004-10-29",
    owned: true,
    platforms: ["Microsoft Xbox"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "We Love Katamari",
    image: "co6me1",
    series: "Katamari",
    release: "2006-02-02",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Tokobot Plus: Mysteries of the Karakuri",
    image: "co2xc8",
    series: "Tokobot",
    release: "2006-11-17",
    owned: true,
    platforms: ["Sony PlayStation 2"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Tekken 3",
    image: "co8d7r",
    series: "Tekken",
    release: "1998-09-12",
    owned: true,
    platforms: ["Sony PlayStation"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Tomb Raider III: Adventures of Lara Croft",
    image: "co54lh",
    series: "Tomb Raider",
    release: "1998-11-20",
    owned: true,
    platforms: ["Sony PlayStation"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Street Fighter Alpha 3",
    image: "co6akw",
    series: "Street Fighter",
    release: "1999-6-25",
    owned: true,
    platforms: ["Sony PlayStation"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dungeon Keeper Gold",
    image: "co7v6r",
    series: "Dungeon Keeper",
    release: "1998-03-01",
    owned: true,
    platforms: ["Microsoft Windows"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Hocus Pocus",
    image: "co4m3q",
    release: "1994-06-01",
    owned: true,
    platforms: ["MS-DOS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Pokémon Play It!",
    image: "co2ojw",
    series: "Pokémon",
    release: "2000-02-01",
    owned: true,
    platforms: ["Microsoft Windows"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Descent",
    image: "co1xmo",
    series: "Descent",
    release: "1995-03-03",
    owned: true,
    platforms: ["MS-DOS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Halloween Harry in Zombie Wars",
    image: "co5d9k",
    series: "Halloween Harry",
    release: "1996-12-01",
    owned: true,
    platforms: ["Microsoft Windows"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dark Colony",
    image: "co2mn9",
    release: "1997-02-01",
    owned: true,
    platforms: ["Microsoft Windows"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Warhammer: Dark Omen",
    image: "co52vo",
    series: "Warhammer",
    release: "1998-03-31",
    owned: true,
    platforms: ["Microsoft Windows"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Theme Hospital",
    image: "co3wfx",
    series: "Theme",
    release: "1997-02-04",
    owned: true,
    platforms: ["Microsoft Windows"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wii Play",
    image: "co8kn9",
    series: "Wii Play",
    release: "2006-12-08",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wii Sports",
    image: "co3vge",
    series: "Wii Sports",
    release: "2006-12-08",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wii Sports Resort",
    image: "co2may",
    series: "Wii Sports",
    release: "2009-07-24",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wii Fit Plus",
    image: "co86mm",
    series: "Wii Fit",
    release: "2009-10-30",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Punch-Out!!",
    image: "co2f72",
    series: "Punch-Out!!",
    release: "2009-05-22",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "MadWorld",
    image: "co22ou",
    release: "2009-03-20",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario Kart Wii",
    image: "co214e",
    series: "Mario Kart",
    release: "2008-04-11",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Nights: Journey of Dreams",
    image: "co25aw",
    series: "Nights",
    release: "2008-01-18",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mini Ninjas",
    image: "co21i5",
    series: "Mini Ninjas",
    release: "2009-09-11",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Tatsunoko vs. Capcom: Ultimate All Stars",
    image: "co1ydx",
    series: "Capcom Versus",
    release: "2010-01-29",
    owned: true,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Bayonetta 3",
    image: "co4z2i",
    series: "Bayonetta",
    release: "2022-10-28",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 19,
    type: "games",
  },
  {
    name: "Bayonetta 2",
    image: "co7o0m",
    series: "Bayonetta",
    release: "2018-2-16",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 13,
    type: "games",
  },
  {
    name: "Kirby and the Forgotten Land",
    image: "co3vlw",
    series: "Kirby",
    release: "2022-03-25",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 16,
    type: "games",
  },
  {
    name: "Kirby Star Allies",
    image: "co8ezz",
    series: "Kirby",
    release: "2018-03-16",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 9,
    type: "games",
  },
  {
    name: "WarioWare: Move It!",
    image: "co6nwc",
    series: "WarioWare",
    release: "2023-11-03",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 4,
    type: "games",
  },
  {
    name: "Donkey Kong Country: Tropical Freeze",
    image: "co7pmi",
    series: "Donkey Kong Country",
    release: "2018-05-04",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 20,
    type: "games",
  },
  {
    name: "Sonic Mania Plus",
    image: "co1upn",
    series: "Sonic the Hedgehog",
    release: "2018-07-17",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 10,
    type: "games",
  },
  {
    name: "Sonic Origin Plus",
    image: "co6oez",
    series: "Sonic the Hedgehog",
    release: "2023-06-23",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 11,
    type: "games",
  },
  {
    name: "Sonic Superstars",
    image: "co6nm2",
    series: "Sonic the Hedgehog",
    release: "2023-10-17",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 10,
    type: "games",
  },
  {
    name: "Super Mario RPG",
    image: "co7pjz",
    release: "2023-11-17",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 14,
    type: "games",
  },
  {
    name: "Dead Cells: Return to Castlevania Edition",
    image: "co7jf7",
    release: "2023-08-11",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 30,
    type: "games",
  },
  {
    name: "Metal Gear Solid Master Collection: Volume 1",
    image: "co6jaw",
    release: "2023-10-24",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 48,
    type: "games",
  },
  {
    name: "Pac-Man World Re-Pac",
    image: "co7ex1",
    series: "Pac-Man World",
    release: "2022-08-26",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 7,
    type: "games",
  },
  {
    name: "Star Ocean: The Second Story R",
    image: "co6nmh",
    series: "Star Ocean",
    release: "2023-11-02",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 34,
    type: "games",
  },
  {
    name: "Disney Classic Games Collection",
    image: "co7x1m",
    release: "2021-12-03",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 5,
    type: "games",
  },
  {
    name: "Eastward",
    image: "co3tul",
    release: "2021-09-16",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 25,
    type: "games",
  },
  {
    name: "Live A Live",
    image: "co7rur",
    release: "2022-07-22",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 27,
    type: "games",
  },
  {
    name: "Sea of Stars",
    image: "co215b",
    release: "2023-08-29",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 35,
    type: "games",
  },
  {
    name: "Snipperclips Plus: Cut It Out, Together!",
    image: "co7por",
    release: "2017-11-09",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 8,
    type: "games",
  },
  {
    name: "Pocky & Rocky Reshrined",
    image: "co4ctq",
    series: "Pocky & Rocky",
    release: "2022-06-24",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 4,
    type: "games",
  },
  {
    name: "​The Ninja Saviors: Return of the Warriors",
    image: "co4spw",
    series: "Ninja Warriors",
    release: "2019-08-30",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 4,
    type: "games",
  },
  {
    name: "Double Dragon Gaiden: Rise of the Dragons",
    image: "co6g6l",
    series: "Double Dragon",
    release: "2023-07-27",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 6,
    type: "games",
  },
  {
    name: "Streets of Rage 4: Anniversary Edition",
    image: "co3gnx",
    series: "Streets of Rage",
    release: "2021-09-24",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 8,
    type: "games",
  },
  {
    name: "Teenage Mutant Ninja Turtles: Shredder's Revenge",
    image: "co5srs",
    series: "Teenage Mutant Ninja Turtles",
    release: "2022-06-16",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 4,
    type: "games",
  },
  {
    name: "Princess Peach: Showtime!",
    image: "co835c",
    series: "Princess Peach",
    release: "2024-03-22",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 9,
    type: "games",
  },
  {
    name: "Super Mario Bros. Wonder",
    image: "co6nnl",
    series: "Super Mario",
    release: "2023-10-20",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 14,
    type: "games",
  },
  {
    name: "Super Mario Odyssey",
    image: "co1mxf",
    series: "Super Mario",
    release: "2017-10-27",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 27,
    type: "games",
  },
  {
    name: "Bloodstained: Ritual of the Night",
    image: "co5qgf",
    series: "Bloodstained",
    release: "2019-06-25",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 22,
    type: "games",
  },
  {
    name: "Mario & Luigi: Superstar Saga + Bowser's Minions",
    image: "co6qbp",
    series: "Mario & Luigi",
    release: "2017-10-06",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 28,
    type: "games",
  },
  {
    name: "Mario & Luigi: Paper Jam",
    image: "co4ahr",
    series: "Mario & Luigi",
    release: "2015-12-04",
    owned: true,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 32,
    type: "games",
  },
  {
    name: "Another Code: Recollection",
    image: "co72z3",
    series: "Another Code",
    release: "2024-01-19",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 16,
    type: "games",
  },
  {
    name: "Emio: The Smiling Man: Famicom Detective Club",
    image: "co8ixy",
    series: "Famicom Detective Club",
    release: "2024-08-29",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 12,
    type: "games",
  },
  {
    name: "Shadow of the Ninja Reborn",
    image: "co6yek",
    series: "Shadow of the Ninja",
    release: "2024-08-29",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 8,
    type: "games",
  },
  {
    name: "Dragon Quest III: HD-2D Remake",
    image: "co8d90",
    series: "Dragon Quest",
    release: "2024-11-14",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 40,
    type: "games",
  },
  {
    name: "The Legend of Zelda: Echoes of Wisdom",
    image: "co8d9b",
    series: "The Legend of Zelda",
    release: "2024-09-26",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: true,
    hours: 30,
    type: "games",
  },
  {
    name: "Mario & Luigi: Brothership",
    image: "co8d9a",
    series: "Mario & Luigi",
    release: "2024-11-07",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 50,
    type: "games",
  },
  {
    name: "Tomb Raider I-III Remastered Starring Lara Croft",
    image: "co8xte",
    series: "Tomb Raider",
    release: "2024-02-14",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 60,
    type: "games",
  },
  {
    name: "Metroid Fusion",
    image: "co3w49",
    series: "Metroid",
    release: "2002-11-22",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 6,
    type: "games",
  },
  {
    name: "Prince of Persia: The Lost Crown",
    image: "co6lli",
    series: "Prince of Persia",
    release: "2024-01-18",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 24,
    type: "games",
  },
  {
    name: "We Love Katamari Reroll + Royal Reverie",
    image: "co6589",
    series: "Katamari",
    release: "2023-06-02",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 16,
    type: "games",
  },
  {
    name: "Donkey Kong Country Returns HD",
    image: "co8d9n",
    series: "Donkey Kong Country",
    release: "2025-01-16",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 18,
    type: "games",
  },
  {
    name: "Mario & Luigi: Superstar Saga",
    image: "co21rg",
    series: "Mario & Luigi",
    release: "2003-11-21",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Magical Starsign",
    image: "co4py6",
    series: "Magical Starsign",
    release: "2007-02-09",
    owned: true,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sword of Mana",
    image: "co4pw9",
    series: "Mana",
    release: "2004-03-18",
    owned: true,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania",
    image: "co5geb",
    series: "Castlevania",
    release: "1999-05-14",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Legacy of Darkness",
    image: "co54ti",
    series: "Castlevania",
    release: "2000-03-03",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby 64: The Crystal Shards",
    image: "co1wcz",
    series: "Kirby",
    release: "2001-06-22",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario Kart 64",
    image: "co67hm",
    series: "Mario Kart",
    release: "1997-06-24",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mischief Makers",
    image: "co29no",
    series: "Mischief Makers",
    release: "1998-01-15",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Paper Mario",
    image: "co1qda",
    series: "Paper Mario",
    release: "2001-10-05",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario 64",
    image: "co721v",
    series: "Super Mario",
    release: "1997-03-01",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Smash Bros.",
    image: "co2tso",
    series: "Super Smash Bros.",
    release: "1999-11-19",
    owned: false,
    platforms: ["Nintendo 64"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Luigi's Mansion",
    image: "co1wr1",
    series: "Luigi's Mansion",
    release: "2002-05-03",
    owned: false,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario Kart: Double Dash!!",
    image: "co7ndu",
    series: "Mario Kart",
    release: "2003-11-14",
    owned: false,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Paper Mario: The Thousand-Year Door",
    image: "co25us",
    series: "Paper Mario",
    release: "2004-11-12",
    owned: false,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Mario Sunshine",
    image: "co21rh",
    series: "Super Mario",
    release: "2002-10-04",
    owned: false,
    platforms: ["Nintendo GameCube"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Epic Yarn",
    image: "co1w9w",
    series: "Kirby",
    release: "2011-02-25",
    owned: false,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Rhythm Heaven Fever",
    image: "co2klu",
    series: "Rhythm Heaven",
    release: "2012-07-06",
    owned: false,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Metroid: Other M",
    image: "co3m7m",
    series: "Metroid",
    release: "2010-09-03",
    owned: false,
    platforms: ["Nintendo Wii"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Smash Bros. for Nintendo Wii U",
    image: "co213x",
    series: "Super Smash Bros.",
    release: "2014-11-28",
    owned: false,
    platforms: ["Nintendo Wii U"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: The Adventure",
    image: "co7j1d",
    series: "Castlevania",
    release: "1991-08-08",
    owned: false,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania II: Belmont's Revenge",
    image: "co1tg9",
    series: "Castlevania",
    release: "1992-11-26",
    owned: false,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania Legends",
    image: "co20d8",
    series: "Castlevania",
    release: " 1998-01-01",
    owned: false,
    platforms: ["Nintendo Game Boy"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Block Ball",
    image: "co7pmh",
    series: "Kirby",
    release: "1996-08-29",
    owned: false,
    platforms: ["Nintendo Game Boy"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby's Pinball Land",
    image: "co4qv2",
    series: "Kirby",
    release: "1993-12-01",
    owned: false,
    platforms: ["Nintendo Game Boy"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Metroid II: Return of Samus",
    image: "co1wwx",
    series: "Metroid",
    release: "1992-05-21",
    owned: false,
    platforms: ["Nintendo Game Boy"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wario Land II",
    image: "co4qfz",
    series: "Wario Land",
    release: "1998-03-26",
    owned: false,
    platforms: ["Nintendo Game Boy", "Nintendo Game Boy Color"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Classic NES Series: Castlevania",
    image: "co3dbs",
    series: "Castlevania",
    release: "2005-01-07",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Classic NES Series: Metroid",
    image: "co4kzc",
    series: "Metroid",
    release: "2005-01-07",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Classic NES Series: Super Mario Bros.",
    image: "co3axg",
    series: "Super Mario Bros.",
    release: "2004-07-09",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Aria of Sorrow",
    image: "co1nh5",
    series: "Castlevania",
    release: "2003-05-09",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Circle of the Moon",
    image: "co2zq1",
    series: "Castlevania",
    release: "2001-06-22",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Harmony of Dissonance",
    image: "co5otg",
    series: "Castlevania",
    release: "2002-10-11",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Metroid: Zero Mission",
    image: "co1vci",
    series: "Metroid",
    release: "2004-04-08",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Pokémon: FireRed Version",
    image: "co1ziq",
    series: "Pokémon",
    release: "2004-10-01",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Dawn of Sorrow",
    image: "co3dc0",
    series: "Castlevania",
    release: "2005-09-30",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Portrait of Ruin",
    image: "co4ajg",
    series: "Castlevania",
    release: "2007-03-09",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Order of Ecclesia",
    image: "co1nha",
    series: "Castlevania",
    release: "2008-02-06",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Freshly-Picked Tingle's Rosy Rupeeland",
    image: "co2ymm",
    series: "Tingle",
    release: "2007-09-14",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: true,
    hours: 0,
    type: "games",
  },
  {
    name: "Kirby Canvas Curse",
    image: "co1qov",
    series: "Kirby",
    release: "2005-11-25",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario & Luigi: Partners in Time",
    image: "co21rk",
    series: "Mario & Luigi",
    release: "2006-01-27",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario & Luigi: Bowser's Inside Story",
    image: "co21vr",
    series: "Mario & Luigi",
    release: "2009-10-09",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Super Princess Peach",
    image: "co1wsg",
    series: "Princess Peach",
    release: "2006-05-26",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Pokémon SoulSilver Version",
    image: "co1z59",
    series: "Pokémon",
    release: "2010-03-26",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Castlevania: Lords of Shadow - Mirror of Fate",
    image: "co1pat",
    series: "Castlevania",
    release: "2013-03-08",
    owned: false,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario & Luigi: Dream Team",
    image: "co4ahq",
    series: "Mario & Luigi",
    release: "2013-07-12",
    owned: false,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey",
    image: "co22a8",
    series: "Mario & Luigi",
    release: "2019-01-25",
    owned: false,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Mario Kart 8 Deluxe",
    image: "co213p",
    series: "Mario Kart",
    release: "2007-04-28",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Adventure",
    image: "co5jae",
    series: "Sonic the Hedgehog",
    release: "1999-10-14",
    owned: false,
    platforms: ["Sega Dreamcast"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Adventure 2",
    image: "co1te4",
    series: "Sonic the Hedgehog",
    release: "2001-06-23",
    owned: false,
    platforms: ["Sega Dreamcast"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Rush",
    image: "co3zfe",
    series: "Sonic the Hedgehog",
    release: "2005-11-18",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Rush Adventure",
    image: "co1zvk",
    series: "Sonic the Hedgehog",
    release: "2007-09-13",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Lost World",
    image: "co1tzk",
    series: "Sonic the Hedgehog",
    release: "2013-10-18",
    owned: false,
    platforms: ["Nintendo Wii U"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic Colors: Ultimate",
    image: "co31a0",
    series: "Sonic the Hedgehog",
    release: "2021-09-07",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sonic X Shadow Generations",
    image: "co8byo",
    series: "Sonic the Hedgehog",
    release: "2024-10-25",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Octopath Traveler",
    image: "co4kap",
    series: "Octopath Traveler",
    release: "2018-07-13",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Octopath Traveler II",
    image: "co7ds7",
    series: "Octopath Traveler",
    release: "2023-02-24",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "LISA: Definitive Edition",
    image: "co6l8z",
    series: "Lisa",
    release: "2023-07-18",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Radiant Historia: Perfect Chronology",
    image: "co26im",
    series: "Radiant Historia",
    release: "2018-02-12",
    owned: false,
    platforms: ["Nintendo 3DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Final Fantasy IV Advance",
    image: "co2yc0",
    series: "Final Fantasy",
    release: "2006-02-23",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Final Fantasy VI Advance",
    image: "co2yh2",
    series: "Final Fantasy",
    release: "2007-06-29",
    owned: false,
    platforms: ["Nintendo Game Boy Advance"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Sands of Destruction",
    image: "co2w9y",
    series: "Sands of Destruction",
    release: "2010-01-12",
    owned: false,
    platforms: ["Nintendo DS"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Virgo Versus the Zodiac",
    image: "co8uod",
    series: "Virgo",
    release: "2023-08-23",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Blasphemous II",
    image: "co6ej3",
    series: "Blasphemous",
    release: "2023-08-24",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Lunar Remastered Collection",
    image: "co8v0l",
    series: "Lunar",
    release: "2025-04-18",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "The Messenger",
    image: "co2hr9",
    series: "The Messenger",
    release: "2018-08-30",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Legacy of Kain: Soul Reaver 1 & 2 Remastered",
    image: "co8urj",
    series: "Legacy of Kain",
    release: "2024-12-10",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Wild Guns Reloaded",
    image: "co23qm",
    series: "Wild Guns",
    release: "2018-04-17",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Ultros",
    image: "co7i3x",
    series: "Ultros",
    release: "2025-02-13",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Suikoden I & II HD Remaster: Gate Rune and Dunan Unification Wars",
    image: "co5aak",
    series: "Suikoden",
    release: "2025-03-06",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Beyond the Ice Palace II",
    image: "co82o9",
    series: "Beyond the Ice Palace",
    release: "2025-03-10",
    owned: true,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Shadow Labyrinth",
    image: "co95ft",
    series: "Pac-Man",
    release: "2025-12-31",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Metroid Prime 4: Beyond",
    image: "co8d8c",
    series: "Metroid",
    release: "2025-12-31",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
  {
    name: "Dragon Quest I & II: HD-2D Remake",
    image: "co8d97",
    series: "Dragon Quest",
    release: "2025-12-31",
    owned: false,
    platforms: ["Nintendo Switch"],
    completed: false,
    hours: 0,
    type: "games",
  },
];
