export const hardware = [
  {
    name: "Game & Watch: The Legend of Zelda",
    image: "game-watch-zelda",
    company: "Nintendo",
    series: "Game & Watch",
    format: "Handheld",
    release: "2021-11-12",
    owned: true,
    type: "hardware",
  },
  {
    name: "Game & Watch: Super Mario Bros.",
    image: "game-watch-mario",
    company: "Nintendo",
    series: "Game & Watch",
    format: "Handheld",
    release: "2020-11-13",
    owned: true,
    type: "hardware",
  },
  {
    name: "Game Boy (Off White)",
    image: "game-boy",
    company: "Nintendo",
    series: "Game Boy",
    format: "Handheld",
    release: "1990-09-28",
    owned: false,
    type: "hardware",
  },
  {
    name: "Game Boy Color (Atomic Purple)",
    image: "gbc",
    company: "Nintendo",
    series: "Game Boy",
    format: "Handheld",
    release: "1998-11-23",
    owned: true,
    type: "hardware",
  },
  {
    name: "Game Boy Advance (Glacier)",
    image: "game-boy-advance",
    company: "Nintendo",
    series: "Game Boy",
    format: "Handheld",
    release: "2001-06-22",
    owned: true,
    type: "hardware",
  },
  {
    name: "Game Boy Advance (White)",
    image: "gba-white",
    company: "Nintendo",
    series: "Game Boy",
    format: "Handheld",
    release: "2001-06-22",
    owned: true,
    type: "hardware",
  },
  {
    name: "Game Boy Advance SP (Silver)",
    image: "game-boy-advance-sp",
    company: "Nintendo",
    series: "Game Boy",
    format: "Handheld",
    release: "2003-03-23",
    owned: true,
    type: "hardware",
  },
  {
    name: "Game Boy Micro",
    image: "game-boy-micro",
    company: "Nintendo",
    series: "Game Boy",
    format: "Handheld",
    release: "2005-11-04",
    owned: false,
    type: "hardware",
  },
  {
    name: "Nintendo DS",
    image: "ds",
    company: "Nintendo",
    series: "DS",
    format: "Handheld",
    release: "2005-03-11",
    owned: false,
    type: "hardware",
  },
  {
    name: "Nintendo DS Lite (White)",
    image: "ds-lite",
    company: "Nintendo",
    series: "DS",
    format: "Handheld",
    release: "2006-06-23",
    owned: false,
    type: "hardware",
  },
  {
    name: "Nintendo DSi XL (Burgundy)",
    image: "ds-i-xl",
    company: "Nintendo",
    series: "DS",
    format: "Handheld",
    release: "2010-03-05",
    owned: false,
    type: "hardware",
  },
  {
    name: "Nintendo 3DS XL",
    image: "3ds-xl",
    company: "Nintendo",
    series: "3DS",
    format: "Handheld",
    release: "2012-07-28",
    owned: false,
    type: "hardware",
  },
  {
    name: "Nintendo 2DS (Blue)",
    image: "2ds",
    company: "Nintendo",
    series: "3DS",
    format: "Handheld",
    release: "2013-10-12",
    owned: false,
    type: "hardware",
  },
  {
    name: "New Nintendo 3DS XL (Orange & Black)",
    image: "new-3ds-xl",
    company: "Nintendo",
    series: "3DS",
    format: "Handheld",
    release: "2017-07-30",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nintendo Classic Mini: Nintendo Entertainment System",
    image: "nes-classic",
    company: "Nintendo",
    series: "Classic Mini",
    format: "Dedicated",
    release: "2016-11-11",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nintendo Classic Mini: Nintendo Entertainment System Controller",
    image: "nes-classic-controller",
    company: "Nintendo",
    series: "Classic Mini",
    format: "Controller",
    release: "2016-11-11",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nintendo Classic Mini: Super Nintendo Entertainment System",
    image: "snes-classic",
    company: "Nintendo",
    series: "Classic Mini",
    format: "Dedicated",
    release: "2017-09-29",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nintendo Classic Mini: Super Nintendo Entertainment System Controller",
    image: "snes-classic-controller",
    company: "Nintendo",
    series: "Classic Mini",
    format: "Controller",
    release: "2017-09-29",
    owned: true,
    type: "hardware",
  },
  {
    name: "GameCube (Platinum)",
    image: "gamecube",
    company: "Nintendo",
    series: "GameCube",
    format: "Home",
    release: "2003-05-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "GameCube Controller (Platinum)",
    image: "gamecube-controller-platinum",
    company: "Nintendo",
    series: "GameCube",
    format: "Controller",
    release: "2003-05-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "GameCube Controller (Indigo)",
    image: "gamecube-controller-indigo",
    company: "Nintendo",
    series: "GameCube",
    format: "Controller",
    release: "2002-05-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "GameCube Controller (Jet Black)",
    image: "gamecube-controller-jet-black",
    company: "Nintendo",
    series: "GameCube",
    format: "Controller",
    release: "2002-05-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "GameCube Controller (Spice Orange)",
    image: "gamecube-controller-spice-orange",
    company: "Nintendo",
    series: "GameCube",
    format: "Controller",
    release: "2001-11-18",
    owned: true,
    type: "hardware",
  },
  {
    name: "GameCube Controller (Emerald Blue)",
    image: "gamecube-controller-emerald-blue",
    company: "Nintendo",
    series: "GameCube",
    format: "Controller",
    release: "2002-12-05",
    owned: true,
    type: "hardware",
  },
  {
    name: "Game Boy Player Controller (Indigo)",
    image: "game-boy-controller",
    company: "Nintendo",
    series: "GameCube",
    format: "Controller",
    release: "2003-09-14",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii (White)",
    image: "wii",
    company: "Nintendo",
    series: "Wii",
    format: "Home",
    release: "2006-12-08",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii Remote Plus (The Legend of Zelda: Skyward Sword Edition)",
    image: "wii-remote-zelda",
    company: "Nintendo",
    series: "Wii",
    format: "Controller",
    release: "2011-11-01",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii Remote Plus (Black)",
    image: "wii-remote-plus-black",
    company: "Nintendo",
    series: "Wii",
    format: "Controller",
    release: "2010-11-05",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii Remote Plus (Red)",
    image: "wii-remote-plus-red",
    company: "Nintendo",
    series: "Wii",
    format: "Controller",
    release: "2010-11-05",
    owned: false,
    type: "hardware",
  },
  {
    name: "Wii Remote (White)",
    image: "wii-remote",
    company: "Nintendo",
    series: "Wii",
    format: "Controller",
    release: "2006-12-08",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nunchuck",
    image: "nunchuck",
    company: "Nintendo",
    series: "Wii",
    format: "Controller",
    release: "2006-12-08",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii mini",
    image: "wii-mini",
    company: "Nintendo",
    series: "Wii",
    format: "Home",
    release: "2013-03-15",
    owned: false,
    type: "hardware",
  },
  {
    name: "Classic Controller Pro (Black)",
    image: "classic-controller-pro",
    company: "Nintendo",
    series: "Wii",
    format: "Controller",
    release: "2009-11-20",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii Balance Board",
    image: "balance-board",
    company: "Nintendo",
    series: "Wii",
    format: "Controller",
    release: "2008-04-26",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii U (Premium)",
    image: "wii-u",
    company: "Nintendo",
    series: "Wii U",
    format: "Home",
    release: "2012-11-30",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii U Gamepad (Black)",
    image: "wii-u-gamepad",
    company: "Nintendo",
    series: "Wii U",
    format: "Controller",
    release: "2012-11-30",
    owned: true,
    type: "hardware",
  },
  {
    name: "Wii U Pro Controller (Black)",
    image: "wii-u-pro-controller",
    company: "Nintendo",
    series: "Wii U",
    format: "Controller",
    release: "2012-11-30",
    owned: true,
    type: "hardware",
  },
  {
    name: "Switch",
    image: "switch",
    company: "Nintendo",
    series: "Switch",
    format: "Hybrid",
    release: "2017-03-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "Switch Lite (Turquoise)",
    image: "switch-lite",
    company: "Nintendo",
    series: "Switch",
    format: "Handheld",
    release: "2019-09-20",
    owned: false,
    type: "hardware",
  },
  {
    name: "Joy-Con (Neon Red & Neon Blue)",
    image: "joy-con-neon",
    company: "Nintendo",
    series: "Switch",
    format: "Controller",
    release: "2017-03-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "Joy-Con (The Legend of Zelda: Skyward Sword HD Edition)",
    image: "joy-con-zelda",
    company: "Nintendo",
    series: "Switch",
    format: "Controller",
    release: "2021-07-16",
    owned: true,
    type: "hardware",
  },
  {
    name: "Switch Pro Controller",
    image: "switch-pro-controller",
    company: "Nintendo",
    series: "Switch",
    format: "Controller",
    release: "2017-03-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nintendo 64 Controller",
    image: "n64-controller",
    company: "Nintendo",
    series: "Switch",
    format: "Controller",
    release: "2021-10-26",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nintendo 64 Controller (Solid Grey)",
    image: "n64-controller-grey",
    company: "Nintendo",
    series: "Nintendo 64",
    format: "Controller",
    release: "1997-03-01",
    owned: false,
    type: "hardware",
  },
  {
    name: "Nintendo 64 Controller (Mario Kart)",
    image: "n64-controller-black",
    company: "Nintendo",
    series: "Nintendo 64",
    format: "Controller",
    release: "1999-02-10",
    owned: true,
    type: "hardware",
  },
  {
    name: "Super Nintendo Entertainment System Controller",
    image: "snes-controller",
    company: "Nintendo",
    series: "Switch",
    format: "Controller",
    release: "2020-03-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "Nintendo 64 (Solid Grey)",
    image: "n64",
    company: "Nintendo",
    series: "64",
    format: "Home",
    release: "1997-03-01",
    owned: false,
    type: "hardware",
  },
  {
    name: "PlayStation 2",
    image: "ps2",
    company: "Sony",
    series: "PlayStation",
    format: "Home",
    release: "2000-11-24",
    owned: false,
    type: "hardware",
  },
  {
    name: "PlayStation 3",
    image: "ps3",
    company: "Sony",
    series: "PlayStation",
    format: "Home",
    release: "2007-03-23",
    owned: true,
    type: "hardware",
  },
  {
    name: "DualShock 2",
    image: "dualshock2",
    company: "Sony",
    series: "PlayStation",
    format: "Controller",
    release: "2000-11-24",
    owned: false,
    type: "hardware",
  },
  {
    name: "DualShock 3",
    image: "dualshock3",
    company: "Sony",
    series: "PlayStation",
    format: "Controller",
    release: "2007-03-23",
    owned: true,
    type: "hardware",
  },
  {
    name: "DualShock 4",
    image: "dualshock4",
    company: "Sony",
    series: "PlayStation",
    format: "Controller",
    release: "2013-11-15",
    owned: true,
    type: "hardware",
  },
  {
    name: "DualSense",
    image: "dualsense",
    company: "Sony",
    series: "PlayStation",
    format: "Controller",
    release: "2020-11-12",
    owned: false,
    type: "hardware",
  },
  {
    name: "PlayStation Classic",
    image: "playstation-classic",
    company: "Sony",
    series: "PlayStation",
    format: "Dedicated",
    release: "2018-12-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "PlayStation Classic Controller",
    image: "playstation-controller",
    company: "Sony",
    series: "PlayStation",
    format: "Controller",
    release: "2018-12-03",
    owned: true,
    type: "hardware",
  },
  {
    name: "PlayStation Portable",
    image: "psp",
    company: "Sony",
    series: "PlayStation",
    format: "Handheld",
    release: "2005-09-01",
    owned: false,
    type: "hardware",
  },
  {
    name: "Mega Drive Mini",
    image: "mega-drive-mini",
    company: "Sega",
    series: "Mega Drive",
    format: "Dedicated",
    release: "2019-09-19",
    owned: true,
    type: "hardware",
  },
  {
    name: "Mega Drive Mini Controller",
    image: "mega-drive-mini-controller",
    company: "Sega",
    series: "Mega Drive",
    format: "Controller",
    release: "2019-09-19",
    owned: true,
    type: "hardware",
  },
  {
    name: "Dreamcast",
    image: "dreamcast",
    company: "Sega",
    series: "Dreamcast",
    format: "Home",
    release: "1999-10-14",
    owned: true,
    type: "hardware",
  },
  {
    name: "Dreamcast Controller",
    image: "dreamcast-controller",
    company: "Sega",
    series: "Dreamcast",
    format: "Controller",
    release: "1999-10-14",
    owned: true,
    type: "hardware",
  },
  {
    name: "Saturn Wireless Controller",
    image: "saturn-wireless-controller",
    company: "Sega",
    series: "Saturn",
    format: "Controller",
    release: "2019-01-01",
    owned: true,
    type: "hardware",
  },
  {
    name: "Atari VCS Classic Controller",
    image: "vcs-classic-controller",
    company: "Atari",
    series: "Atari VCS",
    format: "Controller",
    release: "2021-07-15",
    owned: false,
    type: "hardware",
  },
  {
    name: "The Duke",
    image: "duke",
    company: "MicroSoft",
    series: "Xbox",
    format: "Controller",
    release: "2017-11-01",
    owned: false,
    type: "hardware",
  },
  {
    name: "Xbox 360",
    image: "xbox-360",
    company: "MicroSoft",
    series: "Xbox",
    format: "Home",
    release: "2005-12-02",
    owned: true,
    type: "hardware",
  },
  {
    name: "Xbox 360 Controller",
    image: "xbox-360-controller",
    company: "MicroSoft",
    series: "Xbox",
    format: "Controller",
    release: "2005-12-02",
    owned: true,
    type: "hardware",
  },
  {
    name: "Xbox 360 Wireless Controller",
    image: "xbox-360-wireless-controller",
    company: "MicroSoft",
    series: "Xbox",
    format: "Controller",
    release: "2005-12-02",
    owned: true,
    type: "hardware",
  },
  {
    name: "Xbox Wireless Controller",
    image: "xbox-wireless-controller",
    company: "MicroSoft",
    series: "Xbox",
    format: "Controller",
    release: "2020-10-10",
    owned: true,
    type: "hardware",
  },
];
