export const cards = [
  {
    name: "Game & Watch: The Legend of Zelda",
    cover: "game-watch-zelda",
    company: "Nintendo",
    family: "Game & Watch",
    format: "Handheld",
    owned: true,
  },
  {
    name: "Game & Watch: Super Mario Bros.",
    cover: "game-watch-mario",
    company: "Nintendo",
    family: "Game & Watch",
    format: "Handheld",
    owned: true,
  },
  {
    name: "Game Boy",
    cover: "game-boy",
    company: "Nintendo",
    family: "Game Boy",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Game Boy Color",
    cover: "game-boy-color",
    company: "Nintendo",
    family: "Game Boy",
    format: "Handheld",
    owned: true,
  },
  {
    name: "Game Boy Advance",
    cover: "game-boy-advance",
    company: "Nintendo",
    family: "Game Boy",
    format: "Handheld",
    owned: true,
  },
  {
    name: "Game Boy Advance",
    cover: "gba-white",
    company: "Nintendo",
    family: "Game Boy",
    format: "Handheld",
    owned: true,
  },
  {
    name: "Game Boy Advance SP",
    cover: "game-boy-advance-sp",
    company: "Nintendo",
    family: "Game Boy",
    format: "Handheld",
    owned: true,
  },
  {
    name: "Game Boy Micro",
    cover: "game-boy-micro",
    company: "Nintendo",
    family: "Game Boy",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Nintendo DS",
    cover: "ds",
    company: "Nintendo",
    family: "DS",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Nintendo DS Lite",
    cover: "ds-lite",
    company: "Nintendo",
    family: "DS",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Nintendo DSi XL",
    cover: "ds-i-xl",
    company: "Nintendo",
    family: "DS",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Nintendo 3DS XL",
    cover: "3ds-xl",
    company: "Nintendo",
    family: "3DS",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Nintendo 2DS",
    cover: "2ds",
    company: "Nintendo",
    family: "3DS",
    format: "Handheld",
    owned: false,
  },
  {
    name: "New Nintendo 3DS XL",
    cover: "new-3ds-xl",
    company: "Nintendo",
    family: "3DS",
    format: "Handheld",
    owned: true,
  },
  {
    name: "Nintendo Classic Mini: Nintendo Entertainment System",
    cover: "nes-classic",
    company: "Nintendo",
    family: "Classic Mini",
    format: "Dedicated",
    owned: true,
  },
  {
    name: "Nintendo Classic Mini: Nintendo Entertainment System Controller",
    cover: "nes-classic-controller",
    company: "Nintendo",
    family: "Classic Mini",
    format: "Controller",
    owned: true,
  },
  {
    name: "Nintendo Classic Mini: Super Nintendo Entertainment System",
    cover: "snes-classic",
    company: "Nintendo",
    family: "Classic Mini",
    format: "Dedicated",
    owned: true,
  },
  {
    name: "Nintendo Classic Mini: Super Nintendo Entertainment System Controller",
    cover: "snes-classic-controller",
    company: "Nintendo",
    family: "Classic Mini",
    format: "Controller",
    owned: true,
  },
  {
    name: "GameCube",
    cover: "gamecube",
    company: "Nintendo",
    family: "GameCube",
    format: "Home",
    owned: true,
  },
  {
    name: "GameCube Controller Platinum",
    cover: "gamecube-controller-platinum",
    company: "Nintendo",
    family: "GameCube",
    format: "Controller",
    owned: true,
  },
  {
    name: "GameCube Controller Indigo",
    cover: "gamecube-controller-indigo",
    company: "Nintendo",
    family: "GameCube",
    format: "Controller",
    owned: true,
  },
  {
    name: "GameCube Controller Jet Black",
    cover: "gamecube-controller-jet-black",
    company: "Nintendo",
    family: "GameCube",
    format: "Controller",
    owned: true,
  },
  {
    name: "GameCube Controller Spice Orange",
    cover: "gamecube-controller-spice-orange",
    company: "Nintendo",
    family: "GameCube",
    format: "Controller",
    owned: true,
  },
  {
    name: "GameCube Controller Emerald Blue",
    cover: "gamecube-controller-emerald-blue",
    company: "Nintendo",
    family: "GameCube",
    format: "Controller",
    owned: true,
  },
  {
    name: "Game Boy Player Controller",
    cover: "game-boy-controller",
    company: "Nintendo",
    family: "GameCube",
    format: "Controller",
    owned: true,
  },
  {
    name: "Wii",
    cover: "wii",
    company: "Nintendo",
    family: "Wii",
    format: "Home",
    owned: true,
  },
  {
    name: "Wii Remote Plus The Legend of Zelda: Skyward Sword Edition",
    cover: "wii-remote-zelda",
    company: "Nintendo",
    family: "Wii",
    format: "Controller",
    owned: true,
  },
  {
    name: "Wii Remote Plus Black",
    cover: "wii-remote-plus-black",
    company: "Nintendo",
    family: "Wii",
    format: "Controller",
    owned: true,
  },
  {
    name: "Wii Remote Plus Red",
    cover: "wii-remote-plus-red",
    company: "Nintendo",
    family: "Wii",
    format: "Controller",
    owned: false,
  },
  {
    name: "Wii Remote",
    cover: "wii-remote",
    company: "Nintendo",
    family: "Wii",
    format: "Controller",
    owned: true,
  },
  {
    name: "Nunchuck",
    cover: "nunchuck",
    company: "Nintendo",
    family: "Wii",
    format: "Controller",
    owned: true,
  },
  {
    name: "Wii Mini",
    cover: "wii-mini",
    company: "Nintendo",
    family: "Wii",
    format: "Home",
    owned: false,
  },
  {
    name: "Classic Controller Pro",
    cover: "classic-controller-pro",
    company: "Nintendo",
    family: "Wii",
    format: "Controller",
    owned: true,
  },
  {
    name: "Wii Balance Board",
    cover: "balance-board",
    company: "Nintendo",
    family: "Wii",
    format: "Controller",
    owned: true,
  },
  {
    name: "Wii U",
    cover: "wii-u",
    company: "Nintendo",
    family: "Wii U",
    format: "Home",
    owned: true,
  },
  {
    name: "Wii U Gamepad",
    cover: "wii-u-gamepad",
    company: "Nintendo",
    family: "Wii U",
    format: "Controller",
    owned: true,
  },
  {
    name: "Wii U Pro Controller",
    cover: "wii-u-pro-controller",
    company: "Nintendo",
    family: "Wii U",
    format: "Controller",
    owned: true,
  },
  {
    name: "Nintendo Switch",
    cover: "switch",
    company: "Nintendo",
    family: "Switch",
    format: "Hybrid",
    owned: true,
  },
  {
    name: "Nintendo Switch Lite",
    cover: "switch-lite",
    company: "Nintendo",
    family: "Switch",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Joy-Con Neon Red Neon Blue",
    cover: "joy-con-neon",
    company: "Nintendo",
    family: "Switch",
    format: "Controller",
    owned: true,
  },
  {
    name: "Joy-Con The Legend of Zelda: Skyward Sword HD Edition",
    cover: "joy-con-zelda",
    company: "Nintendo",
    family: "Switch",
    format: "Controller",
    owned: true,
  },
  {
    name: "Nintendo Switch Pro Controller",
    cover: "switch-pro-controller",
    company: "Nintendo",
    family: "Switch",
    format: "Controller",
    owned: true,
  },
  {
    name: "Nintendo 64 Controller",
    cover: "n64-controller",
    company: "Nintendo",
    family: "Switch",
    format: "Controller",
    owned: true,
  },
  {
    name: "Nintendo 64 Controller",
    cover: "n64-controller-grey",
    company: "Nintendo",
    family: "Nintendo 64",
    format: "Controller",
    owned: false,
  },
  {
    name: "Nintendo 64 Controller Black Gray",
    cover: "n64-controller-black",
    company: "Nintendo",
    family: "Nintendo 64",
    format: "Controller",
    owned: true,
  },
  {
    name: "Super Nintendo Entertainment System Controller",
    cover: "snes-controller",
    company: "Nintendo",
    family: "Switch",
    format: "Controller",
    owned: true,
  },
  {
    name: "Nintendo 64",
    cover: "n64",
    company: "Nintendo",
    family: "64",
    format: "Home",
    owned: false,
  },
  {
    name: "PlayStation 2",
    cover: "ps2",
    company: "Sony",
    family: "PlayStation",
    format: "Home",
    owned: false,
  },
  {
    name: "PlayStation 3",
    cover: "ps3",
    company: "Sony",
    family: "PlayStation",
    format: "Home",
    owned: true,
  },
  {
    name: "DualShock 2",
    cover: "dualshock2",
    company: "Sony",
    family: "PlayStation",
    format: "Controller",
    owned: false,
  },
  {
    name: "DualShock 3",
    cover: "dualshock3",
    company: "Sony",
    family: "PlayStation",
    format: "Controller",
    owned: true,
  },
  {
    name: "DualShock 4",
    cover: "dualshock4",
    company: "Sony",
    family: "PlayStation",
    format: "Controller",
    owned: true,
  },
  {
    name: "DualSense",
    cover: "dualsense",
    company: "Sony",
    family: "PlayStation",
    format: "Controller",
    owned: false,
  },
  {
    name: "PlayStation Classic",
    cover: "playstation-classic",
    company: "Sony",
    family: "PlayStation",
    format: "Dedicated",
    owned: true,
  },
  {
    name: "PlayStation Classic Controller",
    cover: "playstation-controller",
    company: "Sony",
    family: "PlayStation",
    format: "Controller",
    owned: true,
  },
  {
    name: "PlayStation Portable",
    cover: "psp",
    company: "Sony",
    family: "PlayStation",
    format: "Handheld",
    owned: false,
  },
  {
    name: "Mega Drive Mini",
    cover: "mega-drive-mini",
    company: "Sega",
    family: "Mega Drive",
    format: "Dedicated",
    owned: true,
  },
  {
    name: "Mega Drive Mini Controller",
    cover: "mega-drive-mini-controller",
    company: "Sega",
    family: "Mega Drive",
    format: "Controller",
    owned: true,
  },
  {
    name: "Dreamcast",
    cover: "dreamcast",
    company: "Sega",
    family: "Dreamcast",
    format: "Home",
    owned: true,
  },
  {
    name: "Dreamcast Controller",
    cover: "dreamcast-controller",
    company: "Sega",
    family: "Dreamcast",
    format: "Controller",
    owned: true,
  },
  {
    name: "Saturn Wireless Controller",
    cover: "saturn-wireless-controller",
    company: "Sega",
    family: "Saturn",
    format: "Controller",
    owned: true,
  },
  {
    name: "Atari VCS Classic Controller",
    cover: "vcs-classic-controller",
    company: "Atari",
    family: "Atari VCS",
    format: "Controller",
    owned: false,
  },
  {
    name: "Duke",
    cover: "duke",
    company: "MicroSoft",
    family: "Xbox",
    format: "Controller",
    owned: false,
  },
  {
    name: "Xbox 360",
    cover: "xbox-360",
    company: "MicroSoft",
    family: "Xbox",
    format: "Home",
    owned: true,
  },
  {
    name: "Xbox 360 Controller",
    cover: "xbox-360-controller",
    company: "MicroSoft",
    family: "Xbox",
    format: "Controller",
    owned: true,
  },
  {
    name: "Xbox 360 Wireless Controller",
    cover: "xbox-360-wireless-controller",
    company: "MicroSoft",
    family: "Xbox",
    format: "Controller",
    owned: true,
  },
  {
    name: "Xbox Wireless Controller",
    cover: "xbox-wireless-controller",
    company: "MicroSoft",
    family: "Xbox",
    format: "Controller",
    owned: true,
  },
];
